### ISSUE TITLE
macOS: switching application language has no effect

### ISSUE THREAD

**Issue by okworx** [GreenDelta/epd-editor#106]
When switching the application's language via the settings dialog, the setting does not go into effect upon restart and seems not to be persisted, as when saving, closing the settings dialog and opening it again, it still shows the previously selected/default language. Could be reproduced under both macOS and Windows 11.

Test case:
- open EPD Editor app on a Windows or macOS system (clean and without having used this app before)
- go to settings dialog
- choose "German" as the application language
- save
- close the application
- launch the application again
- go to settings dialog
- it still shows "English"

The same happens when instead of restarting the settings dialog is reopened after saving and closing.

![EPD_Editor_switch_language](https://github.com/user-attachments/assets/4c982c9f-41cb-467c-84b2-f401fe402ed6)

**Comment by francoislerall** [comment]
Hi Oliver,

Thanks for the feedback. This is actually a bug affecting all OS...
This [commit ](https://github.com/GreenDelta/epd-editor/commit/392d6f7983e3ae79fbf82e88477c5ed70dd70f06) should fix it on all OS.

In the meantime, users could manually edit the `/EPD Editor/EPD Editor.ini` file (by switching from `en` to `de` for example) and restart the EPD Editor.

**Comment by msrocka** [comment]
@francoislerall isn't it also a problem that on macOS the files within the app folder are write-protected and thus the ini file can't be changed by the application? Or did you tested it with a build?

**Comment by francoislerall** [comment]
It could be of course. I did not test to build, we can check when releasing the new version. The thing is that it works on openLCA. So, I have quite some good hope that it will be working there as well.

Also, I might have a better understanding of macOS app now. Applications are not write-protected. They are signed, meaning that if you modify them you cannot copy them on another machine and run it without deactivating the macOS protection.
