### ISSUE TITLE
empty common:other elements are generated

### ISSUE THREAD

**Issue by okworx** [GreenDelta/epd-editor#12]
This is what the EPD-process XML looks like when no subtype has been selected:

```
<LCIMethodAndAllocation>
            <typeOfDataSet>EPD</typeOfDataSet>
            <common:other/>
</LCIMethodAndAllocation>

```

Ideally it should rather look like this:

```
<LCIMethodAndAllocation>
            <typeOfDataSet>EPD</typeOfDataSet>
</LCIMethodAndAllocation>

```

The same can be observed with flow datasets. A newly created flow dataset looks like this:

```
        <f:dataSetInformation>
            <common:UUID>91f638b3-fd72-48d5-8345-96e90df54fbf</common:UUID>
            <f:name>
                <f:baseName xml:lang="de">Steinbutter</f:baseName>
            </f:name>
            <f:classificationInformation/>
            <common:other/>
        </f:dataSetInformation>

```

But should rather look like this

```
        <f:dataSetInformation>
            <common:UUID>91f638b3-fd72-48d5-8345-96e90df54fbf</common:UUID>
            <f:name>
                <f:baseName xml:lang="de">Steinbutter</f:baseName>
            </f:name>
            <f:classificationInformation/>
        </f:dataSetInformation>

```

**Comment by msrocka** [comment]
I could not reproduce this when just creating a new EPD or flow data set in the current version. Are there other steps required to see this?

**Comment by okworx** [comment]
Steps to reproduce:

0. enable XML output
1. create a new product flow and save.
2. create a new EPD dataset
3. in the EPD dataset's "declared product" section, click on the link to assign a product flow.
4. assign the flow from step 1. so far the XML still looks good!
5. save the EPD dataset. now there is an extra <other/> element that wasn't there before.

**Comment by okworx** [comment]
This doesn't seem to be solved completely, as empty `other` elements are still appearing in flow datasets.

Steps to reproduce:

1. enable XML output
2. create a new product flow and save
3. add a material property
4. remove the material property
5. save

This is the XML output that I get (notice the extra `<common:other/>` element):

 ```
<f:flowInformation>
        <f:dataSetInformation>
            <common:UUID>cef650f4-98ec-464c-bbd5-a17b6471af5e</common:UUID>
            <f:name>
                <f:baseName xml:lang="it">New product</f:baseName>
            </f:name>
            <f:classificationInformation/>
            <common:other/>
        </f:dataSetInformation>
    </f:flowInformation>
```
