### ISSUE TITLE
update of product flow should trigger version increment of associated process

### ISSUE THREAD

**Issue by okworx** [GreenDelta/epd-editor#15]
Especially when updating the product flow, it would be more intuitive from a user's perspective if the associated process dataset would be updated as well automagically (and get a version number increment), reflecting the version number increment in the product flow. 

In a way, this is reverse of what's described in #9. We'll need a unified strategy here that provides a choice and appropriate feedback to the user.

**Comment by msrocka** [comment]
I am not sure if this should be labeled as a bug. There is no reference from a product flow to a process (EPD) data set (but the other way around). So this would mean to search the process (or all the processes) where the product is used. If the user then uploads the product, should we also upload the EPD(s) as dependencies?

**Comment by okworx** [comment]
Indeed, the need for update being in reverse direction to the entity dependency doesn't make it easier. A strategy to solve this would be to, upon the modification of a product flow, scan all processes and find out which ones reference the changed product flow. The user would need to be presented with a choice whether to update all of those, only a sub-set or none. 

* Description of the problem/reproduction *

- Create a new product flow, save (flow version: 00.00.001)
- Create a new EPD and attach the previously created product flow
- Save the EPD (EPD version: 00.00.001)
- Edit the product flow (for example, adding a material property) and save (flow version: 00.00.002)
- Upload the EPD to the server including dependencies

Expected results:
The EPD points to the newest version of the flow (flow version: 00.00.002).
The EPD and the newest version of the flow (version 00.00.002) are uploaded to the server.

Observed result:
The EPD points to the previous version of the flow (flow version: 00.00.001).
The EPD and the newest version of the flow (version 00.00.002) are uploaded to the server.


* Workaround *

There's a simple workaround to this issue: After editing a flow, manually increment the version number of the process and save it. (This will make the connection to the flow point to the newest version.) 
Then upload the EPD to the server. The EPD and the newest product flow will be correctly coupled.
