### ISSUE TITLE
invalid ids in flow MatML markup 

### ISSUE THREAD

**Issue by okworx** [GreenDelta/epd-editor#21]
<img width="616" alt="bildschirmfoto 2017-09-15 um 10 40 43" src="https://user-images.githubusercontent.com/9449622/30474082-c13ce2bc-9a02-11e7-881c-8e707c2c29af.png">

The contents of the id attributes that are generated are not valid with respect to their type, causing schema validation to fail.

**Comment by msrocka** [comment]
Right. The editor currently takes the ID of the material property (which is an UUID) as internal ID in the MatML elements. If the UUID starts with a digit this is not valid as the type of the `property` attribute is [xsd:IDREF](http://books.xmlschemata.org/relaxng/ch19-77159.html). I changed the generation of the ID for new material properties. However, this does not solve the issue for existing material properties that were created with an UUID. Moreover, it would be better to generate data set internal IDs for the properties ... but this is a bit more effort to do.

**Comment by msrocka** [comment]
The IDs of material properties that are used in the MatML markup can now be edited:

![matpropids](https://user-images.githubusercontent.com/3520062/31277819-0dec1c58-aaa3-11e7-8e10-13b459f4684b.png)

However, material properties with wrong IDs need to be removed and added again from the respective flow data sets.
