### ISSUE TITLE
auto-adjust column width in validation results table

### ISSUE THREAD

**Issue by okworx** [GreenDelta/epd-editor#27]
It is currently very cumbersome to actually read the validation messages. A simple solution would be to automatically set the column width for the "message" column to the length of the longest entry, so that the value can be read using the horizontal scroll bar of the table.

**Comment by msrocka** [comment]
tried to fix this but SWT tables in forms .... uff

However, a double click on the column header does exactly this.

**Comment by msrocka** [comment]
The column width is now set in the following way: Say that the table has a width of 100%. We give 10% to the UUID column and 10% to the version column. The view where the validation messages are shown is a generic status view where sometimes names are long and the status messages are short or the other way around. Thus, we try to assign the column widths for the name and status message in relation to the content of these columns, with a minimum (maximum) width of 15% (65%) for both columns (we assume that the character width is in average the same for both columns):

```
totalLength = maxNameLenght + maxMessageLength
nameWidth = maxNameLength / totalLength
nameWidth = min(.65, max(.15, nameWidth))
messageWidth = maxMessageLength / totalLength
messageWidth = min(.65, max(.15, messageWidth))
```
