### ISSUE TITLE
Source dataset: non-ASCII filenames causing trouble

### ISSUE THREAD

**Issue by okworx** [GreenDelta/epd-editor#39]
There's a bug in the Jersey library which causes non-ASCII file names to be garbled: [https://github.com/eclipse-ee4j/jersey/issues/3784](https://github.com/eclipse-ee4j/jersey/issues/3784)

As a result, the attachments of a source dataset such as this one

<img width="664" alt="bildschirmfoto 2018-08-30 um 14 28 17" src="https://user-images.githubusercontent.com/9449622/44852152-cd8ad380-ac62-11e8-9150-8d2e66ef84c6.png">

cannot be transferred to the server correctly. 

I suggest to add a warning to the user above this UI element in case any of the files has any non-ASCII characters in its name, recommending to use only letters, numbers, underscores and dashes.

**Comment by msrocka** [comment]
When you add a file with non-ASCII characters, you get the following warning now:

![image](https://user-images.githubusercontent.com/3520062/79225399-ec040980-7e5c-11ea-8770-7d87c0544e66.png)

A warning icon and tooltip is also shown in the table then:

![image](https://user-images.githubusercontent.com/3520062/79225513-1b1a7b00-7e5d-11ea-93f5-2119d0c18deb.png)

**Comment by okworx** [comment]
Great! I suggest to make both messages even more specific by adding what's allowed:
"It is recommended to rename the file first using only letters, numbers, underscores and dashes."

**Comment by msrocka** [comment]
Maybe even `...latin letters, digits...` instead of `...letters, numbers...`

**Comment by okworx** [comment]
true!
