### ISSUE TITLE
Show Reference year after name in navigation tree

### ISSUE THREAD

**Issue by okworx** [GreenDelta/epd-editor#44]
Once there are EPD datasets with the same name but from multiple reference years (thus having a different UUID), they are not distinguishable anymore in the navigation tree, leading to a less-than-optimal UX.

In order to improve this, the reference year could be added after the displayed name in parentheses, e.g.

Foomaterial (2019)

**Comment by okworx** [comment]
The same applies to background database. 

Consider a scenario where a user has a number of EPD datasets in their editor, for example for the same product (so all the datasets have the same name) but from different years and then on top maybe even in one version with GaBi background data and another with ecoinvent background data. This will make it impossible to efficiently navigate. If the navigation tree would show these extra properties it would be easy to differentiate the different datasets.

**Comment by okworx** [comment]
This would apply to both the navigation tree and the dialog for choosing datasets.

**Comment by msrocka** [comment]
Displaying the reference year is done in the main branch now:

![image](https://github.com/GreenDelta/epd-editor/assets/3520062/b1c81073-c1e3-44d6-ad57-036e16a27648)

With the database names it is more complicated: they are typically just added as sources to the dataset (or is there another place?) and there are often many of them:

![image](https://github.com/GreenDelta/epd-editor/assets/3520062/cfd6ba93-0af9-4112-beb3-d3b9ad632776)

I think, concatenating these names makes the navigation not really more user friendly. Also technically it is more complicated: the navigation is based on an index of dataset references that we can quickly build from the stored XML datasets with a dedicated parser. This parser works well and fast for simple tags (like UUID, referenceYear) but would require more work for extracting structured content (but would be possible of course). 

@okworx
