### ISSUE TITLE
expand/collapse options for navigation tree

### ISSUE THREAD

**Issue by okworx** [GreenDelta/epd-editor#45]
"Expand all" and "collapse all" feautures would be nice in order to quickly expand or collapse the navigation tree.

Could be either as entries in the context menu of a root node in the navigation tree or in a tool bar within the navigation view.

**Comment by msrocka** [comment]
@okworx I added this to the menu which maybe is a bit hard to find (on the other hand it is also good to not overload the UI):

![image](https://user-images.githubusercontent.com/3520062/78686562-7dbac680-78f3-11ea-90f5-a2d9a561ad8f.png)

also, our [expand](https://github.com/GreenDelta/epd-editor/blob/master/icons/expand.png) and [collapse](https://github.com/GreenDelta/epd-editor/blob/master/icons/collapse.png) icons are maybe not very helpful
