### ISSUE TITLE
hide password in Server connection dialog

### ISSUE THREAD

**Issue by okworx** [GreenDelta/epd-editor#48]
The password is being displayed as clear text in the dialog; instead, it should be obfuscated for security reasons.

**Comment by msrocka** [comment]
@okworx I changed this in the connection editor:

![image](https://user-images.githubusercontent.com/3520062/78681556-329db500-78ed-11ea-9c91-f0ac97da3e01.png)

Are there other places where this should be fixed? Also note, that the password is still saved as plain text in the stored connections in the user folder `~/.epd-editor/connections/*.json`. But as only the user should have access there it is maybe ok? (I mean for the epd-editor...)

**Comment by okworx** [comment]
That sounds reasonable to me! 👍
