### ISSUE TITLE
Collecting the current dependencies fails

### ISSUE THREAD

**Issue by msrocka** [GreenDelta/epd-editor#56]
`mvn package` currently fails with this error:

```
[ERROR] Failed to execute goal on project dependencies: 
  Could not resolve dependencies for project
  epd-editor:dependencies:pom:1.0.0: 
Failed to collect dependencies at
  com.okworx.ilcd.validation.profiles:EPD-1.1-OEKOBAUDAT:jar:  
    1.0.38: Failed to read artifact descriptor for  
  com.okworx.ilcd.validation.profiles:EPD-1.1-OEKOBAUDAT:jar: 
    1.0.38: Could not find artifact com.okworx.ilcd.validation.profiles:validation-profiles:pom:1.0.0 in central (https://repo.maven.apache.org/maven2)
```

@okworx @diambakus the reason is probably that the [EPD-1.1-OEKOBAUDAT](https://search.maven.org/artifact/com.okworx.ilcd.validation.profiles/EPD-1.1-OEKOBAUDAT/1.0.38/jar) artifact has a parent reference to `com.okworx.ilcd.validation.profiles:validation-profiles:1.0.0` but it cannot find a matching artifact in the central repo? Not sure how this should work with relative path references to a parent:

```xml
<parent>
  <groupId>com.okworx.ilcd.validation.profiles<groupId>
  <artifactId>validation-profiles</artifactId>
  <version>1.0.0</version>
  <relativePath>../..</relativePath>
</parent>
```

@okworx I could not find the profiles repository. So installing from source does not work. (the scm-url from the pom points to a non-public repo? https://bitbucket.org/okusche/ilcdvalidation-profiles.git).

**Comment by okworx** [comment]
Sorry, the parent POM had not yet been released on Central. It should work now.

Here's a PR with the latest version numbers: https://github.com/GreenDelta/epd-editor/pull/57

**Comment by msrocka** [comment]
@okworx great. This is fixed now. It took a bit until it was available in the central repo but it should be all good now. Thanks!
