### ISSUE TITLE
more empty elements for new fields for ILCD+EPD v1.2

### ISSUE THREAD

**Issue by okworx** [GreenDelta/epd-editor#59]
Some empty `<common:commissionerAndGoal/>` elements have been spotted in the wild which shouldn't be there as they cause unnecessary complaints by the validation.

**Comment by msrocka** [comment]
But in the schema all sub-elements of this type are defined as optional:

![image](https://user-images.githubusercontent.com/3520062/111596242-3c05f180-87cd-11eb-8228-f3dc2c29edee.png)

So maybe the validation is maybe a bit too strict here?

**Comment by okworx** [comment]
That is indeed correct. A completely emtpy `<common:commissionerAndGoal/>` is valid as per the schema and validation rules. 
What's not allowed if there's an empty `<common:referenceToCommissioner/>` inside w/o either `refObjectId` or `uri` attributes, that'll raise a complaint by the validation rules as it can't be enforced by the schema.
Thanks for fixing this anyway, it's always nicer not to have any emtpy elements floating around.
