### ISSUE TITLE
network connection (read) to node fails

### ISSUE THREAD

**Issue by okworx** [GreenDelta/epd-editor#67]
Test case:

- starting on a clean installation
- add a server connection
- set URL to `https://www.oekobaudat.de/OEKOBAU.DAT/resource`
- leave User and Password empty
- try to select a data stock by selecting the "None" label under "Data stock"

Observed behavior:

- an error message will appear:

<img width="434" alt="image" src="https://user-images.githubusercontent.com/9449622/121051156-82aa2d00-c7b9-11eb-9f5e-1f75a475c66c.png">

Expected behavior: 

- a list of data stocks appears to select from

Furthermore, the pre-configured server connection appears only after a new connection has been added, and its format looks a bit strange:

<img width="307" alt="image" src="https://user-images.githubusercontent.com/9449622/121052520-bf2a5880-c7ba-11eb-85ff-8ca378bc7fee.png">

**Comment by msrocka** [comment]
should be fixed in this pre-release now: https://github.com/GreenDelta/epd-editor/releases/tag/v5.0.0

![image](https://user-images.githubusercontent.com/3520062/121691305-2865e080-cac7-11eb-97d0-23166dc1a423.png)
