### ISSUE TITLE
Categories: add option to display category IDs

### ISSUE THREAD

**Issue by okworx** [GreenDelta/epd-editor#76]
For ÖKOBAUDAT, each category has an ID number which is frequently being referred to:

<img width="447" alt="CleanShot 2022-10-24 at 11 21 35@2x" src="https://user-images.githubusercontent.com/9449622/197493258-1915ac73-b1b5-41d5-8036-f17a8dbdef9d.png">

It would be a nice addition to display this number in the category selection dialog:
![image001](https://user-images.githubusercontent.com/9449622/197493021-9a442f23-f472-4199-9335-a633e8a451df.png)

There could be a checkbox in the settings that controls this globally (disabled by default) and maybe another checkbox on the category selection dialog to be able to override that global setting on demand.

**Comment by msrocka** [comment]
This will be done in 5.1.0. To make it backwards compatible, we added the option "Hide category IDs in navigation" which is disabled by default. Also, we only display category IDs when they are reasonable short (so e.g. no UUIDs).

A bit related to that: in the navigation we always show all category systems that are used in the datasets. Some of them do not have IDs. A nice addition would be that the users can select which category system should be displayed in the navigation.
