### ISSUE TITLE
macOS app declined v5.0.0_2021-06-11

### ISSUE THREAD

**Issue by urms** [GreenDelta/epd-editor#77]
The macOS app from here: https://github.com/GreenDelta/epd-editor/releases/download/v5.0.0/epd-editor_macOS_5.0.0_2021-06-11.tar.gz 
epd-editor.app is declined / considered damaged by macOS 13.0.1 (22A400) Ventura on an MBP 2020 M1.

<img width="409" alt="Bildschirm­foto 2022-11-24 um 17 02 49" src="https://user-images.githubusercontent.com/1894449/203826766-47260f55-1bd2-49c6-bb9e-81cd89727311.png">

**Comment by msrocka** [comment]
Thank you for reporting this. I think it is the same issue like here with the same possible workarounds: https://github.com/GreenDelta/olca-app/issues/152

**Comment by urms** [comment]
Thanks a alot - works!

**Comment by msrocka** [comment]
A signed version for macOS will be available with v6.0
